
import type { Language, TransformationDB, Artist } from './types';

export const LANGUAGES: { value: Language; label: string, short: string }[] = [
  { value: 'fr', label: 'Français', short: 'FR' },
  { value: 'en', label: 'English', short: 'EN' },
  { value: 'es', label: 'Español', short: 'ES' },
];

export const ARTISTS: Artist[] = [
  { name: "Botticelli", style_fr: "Renaissance", style_en: "Renaissance", style_es: "Renacimiento" },
  { name: "Brueghel", style_fr: "Renaissance / Maniérisme", style_en: "Renaissance / Mannerism", style_es: "Renacimiento / Manierismo" },
  { name: "Leonardo Da Vinci", style_fr: "Renaissance", style_en: "Renaissance", style_es: "Renacimiento" },
  { name: "Michel-Ange", style_fr: "Renaissance", style_en: "Renaissance", style_es: "Renacimiento" },
  { name: "Rafael", style_fr: "Renaissance", style_en: "Renaissance", style_es: "Renacimiento" },
  { name: "Vermeer", style_fr: "Baroque", style_en: "Baroque", style_es: "Barroco" },
  { name: "Rubens", style_fr: "Baroque", style_en: "Baroque", style_es: "Barroco" },
  { name: "Rembrandt", style_fr: "Baroque", style_en: "Baroque", style_es: "Barroco" },
  { name: "Caravaggio", style_fr: "Baroque", style_en: "Baroque", style_es: "Barroco" },
  { name: "Goya", style_fr: "Romantisme", style_en: "Romanticism", style_es: "Romanticismo" },
  { name: "William Turner", style_fr: "Romantisme", style_en: "Romanticism", style_es: "Romanticismo" },
  { name: "Douanier Rousseau", style_fr: "Naïf / Postimpressionnisme", style_en: "Naïve Art / Post-Impressionism", style_es: "Arte Naíf / Postimpresionismo" },
  { name: "Cézanne", style_fr: "Postimpressionnisme", style_en: "Post-Impressionism", style_es: "Postimpresionismo" },
  { name: "Toulouse-Lautrec", style_fr: "Postimpressionnisme", style_en: "Post-Impressionism", style_es: "Postimpresionismo" },
  { name: "Vincent van Gogh", style_fr: "Postimpressionnisme", style_en: "Post-Impressionism", style_es: "Postimpresionismo" },
  { name: "Claude Monet", style_fr: "Impressionnisme", style_en: "Impressionism", style_es: "Impresionismo" },
  { name: "Modigliani", style_fr: "Expressionnisme / Modernisme", style_en: "Expressionism / Modernism", style_es: "Expresionismo / Modernismo" },
  { name: "Diego Rivera", style_fr: "Muralisme / Réalisme social", style_en: "Muralism / Social Realism", style_es: "Muralismo / Realismo Social" },
  { name: "Pablo Picasso", style_fr: "Cubisme", style_en: "Cubism", style_es: "Cubismo" },
  { name: "Juan Gris", style_fr: "Cubisme", style_en: "Cubism", style_es: "Cubismo" },
  { name: "Fernand Léger", style_fr: "Cubisme", style_en: "Cubism", style_es: "Cubismo" },
  { name: "Miro", style_fr: "Surréalisme / Art abstrait", style_en: "Surrealism / Abstract Art", style_es: "Surrealismo / Arte Abstracto" },
  { name: "Salvador Dalí", style_fr: "Surréalisme", style_en: "Surrealism", style_es: "Surrealismo" },
  { name: "Henri Matisse", style_fr: "Fauvisme", style_en: "Fauvism", style_es: "Fauvismo" },
  { name: "Wassily Kandinsky", style_fr: "Abstraction / Bauhaus", style_en: "Abstraction / Bauhaus", style_es: "Abstracción / Bauhaus" },
  { name: "Paul Klee", style_fr: "Bauhaus", style_en: "Bauhaus", style_es: "Bauhaus" },
  { name: "Jackson Pollock", style_fr: "Expressionnisme abstrait", style_en: "Abstract Expressionism", style_es: "Expresionismo Abstracto" },
  { name: "Frida Kahlo", style_fr: "Symbolisme / Naïf", style_en: "Symbolism / Naïve Art", style_es: "Simbolismo / Arte Naíf" },
  { name: "Gustav Klimt", style_fr: "Art nouveau", style_en: "Art Nouveau", style_es: "Art Nouveau" },
  { name: "Georgia O’Keeffe", style_fr: "Modernisme", style_en: "Modernism", style_es: "Modernismo" },
  { name: "Edward Hopper", style_fr: "Réalisme américain", style_en: "American Realism", style_es: "Realismo Americano" },
  { name: "Andy Warhol", style_fr: "Pop art", style_en: "Pop Art", style_es: "Pop Art" },
  { name: "Giuseppe Arcimboldo", style_fr: "Portraits composites", style_en: "Composite Portraits", style_es: "Retratos Compuestos" },
  { name: "Victor Vasarely", style_fr: "Op art, art optique", style_en: "Op Art", style_es: "Op Art / Arte Óptico" },
  { name: "Joseph Beuys", style_fr: "Art conceptuel", style_en: "Conceptual Art", style_es: "Arte Conceptual" },
  { name: "Moebius", style_fr: "Bande dessinée / Science-fiction", style_en: "Comics / Sci-Fi", style_es: "Cómic / Ciencia Ficción" },
  { name: "Hugo Pratt", style_fr: "Bande dessinée / Graphisme", style_en: "Comics / Graphic Art", style_es: "Cómic / Grafismo" },
  { name: "John Maeda", style_fr: "Art génératif et numérique", style_en: "Generative & Digital Art", style_es: "Arte Generativo y Digital" },
  { name: "Helena Sarin", style_fr: "Art génératif et numérique", style_en: "Generative & Digital Art", style_es: "Arte Generativo y Digital" },
  { name: "Sofia Crespo", style_fr: "Art génératif et numérique", style_en: "Generative & Digital Art", style_es: "Arte Generativo y Digital" }
];

export const TRANSFORMATIONS_DB: TransformationDB = {
  "format": {
    "category_fr": "Format / Ratio", "category_es": "Formato / Proporción", "category_en": "Format / Aspect Ratio",
    "description_fr": "Choisissez les dimensions de votre image.", "description_es": "Elige las dimensiones de tu imagen.", "description_en": "Choose the dimensions of your image.",
    "transformations": [
      { "categoryKey": "format", "valueKey": "format-auto", "label_fr": "Auto", "label_es": "Auto", "label_en": "Auto", "instruction_fr": "Le format sera déterminé automatiquement.", "instruction_es": "El formato se determinará automáticamente.", "instruction_en": "The format will be determined automatically." },
      { "categoryKey": "format", "valueKey": "format-9_21", "label_fr": "9:21 (Ultra Haut)", "label_es": "9:21 (Ultra Alto)", "label_en": "9:21 (Ultra Tall)", "instruction_fr": "Le format final doit être un portrait ultra haut 9:21.", "instruction_es": "El formato final debe ser un retrato ultra alto 9:21.", "instruction_en": "The final format must be a 9:21 ultra tall portrait." },
      { "categoryKey": "format", "valueKey": "format-9_16", "label_fr": "9:16 (Haut)", "label_es": "9:16 (Alto)", "label_en": "9:16 (Tall)", "instruction_fr": "Le format final doit être un portrait haut 9:16.", "instruction_es": "El formato final debe ser un retrato alto 9:16.", "instruction_en": "The final format must be a 9:16 tall portrait." },
      { "categoryKey": "format", "valueKey": "format-2_3", "label_fr": "2:3 (Portrait)", "label_es": "2:3 (Retrato)", "label_en": "2:3 (Portrait)", "instruction_fr": "Le format final doit être un portrait 2:3.", "instruction_es": "El formato final debe ser un retrato 2:3.", "instruction_en": "The final format must be a 2:3 portrait." },
      { "categoryKey": "format", "valueKey": "format-3_4", "label_fr": "3:4 (Portrait)", "label_es": "3:4 (Retrato)", "label_en": "3:4 (Portrait)", "instruction_fr": "Le format final doit être un portrait 3:4.", "instruction_es": "El formato final debe ser un retrato 3:4.", "instruction_en": "The final format must be a 3:4 portrait." },
      { "categoryKey": "format", "valueKey": "format-4_5", "label_fr": "4:5 (Portrait)", "label_es": "4:5 (Retrato)", "label_en": "4:5 (Portrait)", "instruction_fr": "Le format final doit être un portrait 4:5.", "instruction_es": "El formato final debe ser un retrato 4:5.", "instruction_en": "The final format must be a 4:5 portrait." },
      { "categoryKey": "format", "valueKey": "format-1_1", "label_fr": "1:1 (Carré)", "label_es": "1:1 (Cuadrado)", "label_en": "1:1 (Square)", "instruction_fr": "Le format final doit être un carré 1:1.", "instruction_es": "El formato final debe ser un cuadrado 1:1.", "instruction_en": "The final format must be a 1:1 square." },
      { "categoryKey": "format", "valueKey": "format-5_4", "label_fr": "5:4 (Paysage)", "label_es": "5:4 (Paisaje)", "label_en": "5:4 (Landscape)", "instruction_fr": "Le format final doit être un paysage 5:4.", "instruction_es": "El formato final debe ser un paisaje 5:4.", "instruction_en": "The final format must be a 5:4 landscape." },
      { "categoryKey": "format", "valueKey": "format-4_3", "label_fr": "4:3 (Paysage)", "label_es": "4:3 (Paisaje)", "label_en": "4:3 (Landscape)", "instruction_fr": "Le format final doit être un paysage 4:3.", "instruction_es": "El formato final debe ser un paisaje 4:3.", "instruction_en": "The final format must be a 4:3 landscape." },
      { "categoryKey": "format", "valueKey": "format-3_2", "label_fr": "3:2 (Paysage)", "label_es": "3:2 (Paisaje)", "label_en": "3:2 (Landscape)", "instruction_fr": "Le format final doit être un paysage 3:2.", "instruction_es": "El formato final debe ser un paisaje 3:2.", "instruction_en": "The final format must be a 3:2 landscape." },
      { "categoryKey": "format", "valueKey": "format-16_9", "label_fr": "16:9 (Large)", "label_es": "16:9 (Ancho)", "label_en": "16:9 (Wide)", "instruction_fr": "Le format final doit être un paysage large 16:9.", "instruction_es": "El formato final debe ser un paisaje ancho 16:9.", "instruction_en": "The final format must be a 16:9 wide landscape." },
      { "categoryKey": "format", "valueKey": "format-21_9", "label_fr": "21:9 (Ultra Large)", "label_es": "21:9 (Ultra Ancho)", "label_en": "21:9 (Ultrawide)", "instruction_fr": "Le format final doit être un paysage ultra large 21:9.", "instruction_es": "El formato final debe ser un paisaje ultra ancho 21:9.", "instruction_en": "The final format must be a 21:9 ultrawide landscape." },
      { "categoryKey": "format", "valueKey": "format-libre", "label_fr": "✦ Libre (Custom)", "label_es": "✦ Libre (Custom)", "label_en": "✦ Free (Custom)", "instruction_fr": "Le format est libre, personnalisé selon le ratio saisi.", "instruction_es": "El formato es libre, personalizado según el ratio ingresado.", "instruction_en": "Free format, customized to the entered aspect ratio." }
    ]
  },
  "framing": {
    "category_fr": "Cadrage", "category_es": "Encuadre", "category_en": "Framing",
    "description_fr": "Quelle est la proximité de la caméra par rapport au sujet ?", "description_es": "¿Qué tan cerca está la cámara del sujeto?", "description_en": "How close is the camera to the subject?",
    "transformations": [
      { "categoryKey": "framing", "valueKey": "framing-macro_shot", "label_fr": "Plan Macro", "label_es": "Plano Macro", "label_en": "Macro Shot", "instruction_fr": "Cadre un plan macro extrême, révélant des détails minuscules.", "instruction_es": "Encuadra un plano macro extremo, revelando detalles diminutos.", "instruction_en": "Frame an extreme macro shot, revealing tiny details." },
      { "categoryKey": "framing", "valueKey": "framing-tight_shot", "label_fr": "Plan Serré", "label_es": "Plano Detalle", "label_en": "Tight Shot", "instruction_fr": "Utilise un plan très serré sur une partie spécifique du sujet.", "instruction_es": "Utiliza un plano detalle sobre una parte específica del sujeto.", "instruction_en": "Use a tight shot on a specific part of the subject." },
      { "categoryKey": "framing", "valueKey": "framing-close_up", "label_fr": "Gros Plan", "label_es": "Primer Plano", "label_en": "Close-Up", "instruction_fr": "Cadre un gros plan sur le sujet, typiquement le visage.", "instruction_es": "Encuadra un primer plano del sujeto, típicamente la cara.", "instruction_en": "Frame a close-up on the subject, typically the face." },
      { "categoryKey": "framing", "valueKey": "framing-medium_close_up", "label_fr": "Plan Rapproché Poitrine", "label_es": "Plano Medio Corto", "label_en": "Medium Close-Up", "instruction_fr": "Cadre le sujet de la tête à la poitrine (plan rapproché poitrine).", "instruction_es": "Encuadra al sujeto de la cabeza al pecho (plano medio corto).", "instruction_en": "Frame the subject from the head to the chest (medium close-up)." },
      { "categoryKey": "framing", "valueKey": "framing-medium_shot", "label_fr": "Plan Rapproché Taille", "label_es": "Plano Medio", "label_en": "Medium Shot", "instruction_fr": "Cadre le sujet de la tête à la taille (plan rapproché taille).", "instruction_es": "Encuadra al sujeto de la cabeza a la cintura (plano medio).", "instruction_en": "Frame the subject from the head to the waist (medium shot)." },
      { "categoryKey": "framing", "valueKey": "framing-italian_shot", "label_fr": "Plan Italien", "label_es": "Plano Italiano", "label_en": "Italian Shot", "instruction_fr": "Cadre le sujet de la tête aux genoux (plan italien).", "instruction_es": "Encuadra al sujeto de la cabeza a las rodillas (plano italiano).", "instruction_en": "Frame the subject from the head to the knees (Italian shot)." },
      { "categoryKey": "framing", "valueKey": "framing-american_shot", "label_fr": "Plan Américain", "label_es": "Plano Americano", "label_en": "American Shot", "instruction_fr": "Cadre le sujet de la tête à mi-cuisse (plan américain).", "instruction_es": "Encuadra al sujeto de la cabeza a medio muslo (plano americano).", "instruction_en": "Frame the subject from the head to mid-thigh (American shot)." },
      { "categoryKey": "framing", "valueKey": "framing-full_shot", "label_fr": "Plan Entier", "label_es": "Plano Entero", "label_en": "Full Shot", "instruction_fr": "Cadre le sujet en entier, de la tête aux pieds.", "instruction_es": "Encuadra al sujeto entero, de la cabeza a los pies.", "instruction_en": "Frame the subject's entire body, from head to toe." },
      { "categoryKey": "framing", "valueKey": "framing-wide_shot", "label_fr": "Plan Large", "label_es": "Plano General", "label_en": "Wide Shot", "instruction_fr": "Utilise un plan large, montrant le sujet dans son environnement.", "instruction_es": "Utiliza un plano general, mostrando al sujeto en su entorno.", "instruction_en": "Use a wide shot, showing the subject in their environment." },
      { "categoryKey": "framing", "valueKey": "framing-extreme_wide_shot", "label_fr": "Plan Très Large", "label_es": "Plano General Largo", "label_en": "Extreme Wide Shot", "instruction_fr": "Utilise un plan très large où l'environnement domine le sujet.", "instruction_es": "Utiliza un plano general largo donde el entorno domina al sujeto.", "instruction_en": "Use an extreme wide shot where the environment dominates the subject." }
    ]
  },
  "camera_angle": {
    "category_fr": "Angle de Caméra", "category_es": "Ángulo de Cámara", "category_en": "Camera Angle",
    "description_fr": "La perspective depuis laquelle le sujet est vu.", "description_es": "La perspectiva desde la que se ve al sujeto.", "description_en": "The perspective from which the subject is viewed.",
    "transformations": [
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-frontal_view", "label_fr": "Vue de Face", "label_es": "Vista Frontal", "label_en": "Frontal View", "instruction_fr": "Cadre le sujet directement de face.", "instruction_es": "Encuadra al sujeto directamente de frente.", "instruction_en": "Frame the subject directly from the front." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-three_quarter_profile", "label_fr": "Trois Quart Profil", "label_es": "Perfil de Tres Cuartos", "label_en": "Three-Quarter Profile", "instruction_fr": "Cadre le sujet de profil trois quarts.", "instruction_es": "Encuadra al sujeto en perfil de tres cuartos.", "instruction_en": "Frame the subject in a three-quarter profile." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-profile_shot", "label_fr": "Profil", "label_es": "Plano de Perfil", "label_en": "Profile Shot", "instruction_fr": "Cadre le sujet de profil strict.", "instruction_es": "Encuadra al sujeto en un estricto plano de perfil.", "instruction_en": "Frame the subject in a strict profile shot." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-rear_view", "label_fr": "Vue Arrière", "label_es": "Vista Trasera", "label_en": "Rear View", "instruction_fr": "Montre la scène depuis l'arrière du sujet.", "instruction_es": "Muestra la escena desde detrás del sujeto.", "instruction_en": "Show the scene from behind the subject." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-eye_level", "label_fr": "Hauteur des Yeux", "label_es": "Nivel de Ojos", "label_en": "Eye-Level", "instruction_fr": "Place la caméra à la hauteur des yeux du sujet.", "instruction_es": "Coloca la cámara a la altura de los ojos del sujeto.", "instruction_en": "Place the camera at the subject's eye level." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-high_angle", "label_fr": "Plongée", "label_es": "Picado", "label_en": "High Angle", "instruction_fr": "Place la caméra en hauteur, en regardant vers le bas (plongée).", "instruction_es": "Coloca la cámara en alto, mirando hacia abajo (picado).", "instruction_en": "Place the camera high, looking down (high angle)." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-low_angle", "label_fr": "Contre-plongée", "label_es": "Contrapicado", "label_en": "Low Angle", "instruction_fr": "Place la caméra en bas, en regardant vers le haut (contre-plongée).", "instruction_es": "Coloca la cámara abajo, mirando hacia arriba (contrapicado).", "instruction_en": "Place the camera low, looking up (low angle)." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-top_down_shot", "label_fr": "Vue Plongeante Verticale", "label_es": "Plano Cenital", "label_en": "Top-Down Shot", "instruction_fr": "Vue verticale, directement d'en haut.", "instruction_es": "Vista vertical, directamente desde arriba.", "instruction_en": "A vertical shot, directly from above." },
      { "categoryKey": "camera_angle", "valueKey": "camera_angle-aerial_view", "label_fr": "Vue Aérienne", "label_es": "Vista Aérea", "label_en": "Aerial View", "instruction_fr": "Vue depuis une grande hauteur, comme si on était dans les airs (vue aérienne).", "instruction_es": "Vista desde una gran altura, como si estuviera en el aire (vista aérea).", "instruction_en": "A view from a great height, as if from the air (aerial view)." }
    ]
  },
  "artistic_styles": {
    "category_fr": "Styles Artistiques", "category_es": "Estilos Artísticos", "category_en": "Artistic Styles",
    "description_fr": "Définissez l'esthétique générale de l'image.", "description_es": "Define la estética general de la imagen.", "description_en": "Define the overall aesthetic of the image.",
    "transformations": [
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-3d_render", "label_fr": "Rendu 3D", "label_es": "Render 3D", "label_en": "3D Render", "instruction_fr": "Donne l'aspect d'un rendu 3D polygoné.", "instruction_es": "Dale el aspecto de un render 3D poligonal.", "instruction_en": "Give the appearance of a polygonal 3D render." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-abstract", "label_fr": "Abstrait", "label_es": "Abstracto", "label_en": "Abstract", "instruction_fr": "Applique un style abstrait, en se concentrant sur les formes et les couleurs plutôt que sur la représentation littérale.", "instruction_es": "Aplica un estilo abstracto, centrándose en las formas y los colores en lugar de la representación literal.", "instruction_en": "Apply an abstract style, focusing on shapes and colors rather than literal representation." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-anime", "label_fr": "Manga / Animé", "label_es": "Manga / Anime", "label_en": "Manga / Anime", "instruction_fr": "Redessine la scène dans un style manga ou animé japonais.", "instruction_es": "Redibuja la escena en un estilo manga o anime japonés.", "instruction_en": "Redraw the scene in a Japanese manga or anime style." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-architectural", "label_fr": "Style Architectural", "label_es": "Estilo Arquitectónico", "label_en": "Architectural Style", "instruction_fr": "Représente la scène comme un dessin architectural, avec des lignes précises et une attention aux détails structurels.", "instruction_es": "Representa la escena como un dibujo arquitectónico, con líneas precisas y atención a los detalles estructurales.", "instruction_en": "Render the scene as an architectural drawing, with precise lines and attention to structural details." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-art_nouveau", "label_fr": "Art Nouveau", "label_es": "Art Nouveau", "label_en": "Art Nouveau", "instruction_fr": "Incorpore des lignes organiques et des motifs décoratifs caractéristiques de l'Art Nouveau.", "instruction_es": "Incorpora líneas orgánicas y patrones decorativos característicos del Art Nouveau.", "instruction_en": "Incorporate organic lines and decorative patterns characteristic of Art Nouveau." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-assemblage", "label_fr": "Art de l'Assemblage", "label_es": "Arte de Ensamblaje", "label_en": "Assemblage Art", "instruction_fr": "Crée l'image comme un 'assemblage', une œuvre tridimensionnelle faite d'objets trouvés.", "instruction_es": "Crea la imagen como un 'ensamblaje', una obra tridimensional hecha de objetos encontrados.", "instruction_en": "Create the image as an 'assemblage', a three-dimensional artwork made from found objects." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-bw", "label_fr": "Noir et Blanc", "label_es": "Blanco y Negro", "label_en": "Black and White", "instruction_fr": "Convertis l'image en noir et blanc.", "instruction_es": "Convierte la imagen en blanco y negro.", "instruction_en": "Convert the image to black and white." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-cartoon", "label_fr": "Dessin Animé", "label_es": "Dibujo Animado", "label_en": "Cartoon", "instruction_fr": "Transforme l'image dans un style de dessin animé, avec des contours audacieux et des couleurs vives.", "instruction_es": "Transforma la imagen en un estilo de dibujo animado, con contornos audaces y colores vivos.", "instruction_en": "Transform the image into a cartoon style, with bold outlines and bright colors." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-collage", "label_fr": "Collage", "label_es": "Collage", "label_en": "Collage", "instruction_fr": "Crée l'image sous forme de collage, en assemblant des morceaux de papier, de photos et d'autres matériaux.", "instruction_es": "Crea la imagen como un collage, ensamblando trozos de papel, fotos y otros materiales.", "instruction_en": "Create the image as a collage, assembling pieces of paper, photos, and other materials." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-comic_book", "label_fr": "Bande Dessinée", "label_es": "Estilo Cómic", "label_en": "Comic Book Style", "instruction_fr": "Donne à l'image un style de bande dessinée, avec des contours d'encre, des couleurs plates et potentiellement des onomatopées.", "instruction_es": "Dale a la imagen un estilo de cómic, con contornos de tinta, colores planos y posiblemente onomatopeyas.", "instruction_en": "Give the image a comic book style, with ink outlines, flat colors, and potential sound effects." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-cubism", "label_fr": "Cubisme", "label_es": "Cubismo", "label_en": "Cubism", "instruction_fr": "Représente le sujet dans un style cubiste, en le décomposant en formes géométriques et en montrant plusieurs points de vue simultanément.", "instruction_es": "Representa al sujeto en un estilo cubista, descomponiéndolo en formas geométricas y mostrando múltiples puntos de vista simultáneamente.", "instruction_en": "Depict the subject in a cubist style, breaking it down into geometric shapes and showing multiple viewpoints simultaneously." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-cyberpunk", "label_fr": "Cyberpunk", "label_es": "Cyberpunk", "label_en": "Cyberpunk", "instruction_fr": "Transforme la scène dans une esthétique cyberpunk (néons, futuriste).", "instruction_es": "Transforma la escena en una estética cyberpunk (neones, futurista).", "instruction_en": "Transform the scene with a cyberpunk aesthetic (neon, futuristic)." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-digital_art", "label_fr": "Art Numérique", "label_es": "Arte Digital", "label_en": "Digital Art", "instruction_fr": "Crée l'image dans un style d'art numérique, avec des lignes nettes et des dégradés lisses, comme si elle était créée sur un ordinateur.", "instruction_es": "Crea la imagen en un estilo de arte digital, con líneas nítidas y degradados suaves, como si fuera creada en un ordenador.", "instruction_en": "Create the image in a digital art style, with clean lines and smooth gradients, as if created on a computer." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-double_exposure", "label_fr": "Double Exposition", "label_es": "Doble Exposición", "label_en": "Double Exposure", "instruction_fr": "Crée un effet de double exposition, en superposant deux images différentes de manière artistique.", "instruction_es": "Crea un efecto de doble exposición, superponiendo dos imágenes diferentes de forma artística.", "instruction_en": "Create a double exposure effect, artistically overlaying two different images." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-famous_artist_style", "label_fr": "Style d'Artiste Célèbre", "label_es": "Estilo de Artista Famoso", "label_en": "Famous Artist Style", "instruction_fr": "Réinterprète la scène dans le style distinctif de {artistName}.", "instruction_es": "Reinterpreta la escena en el estilo distintivo de {artistName}.", "instruction_en": "Reinterpret the scene in the distinctive style of {artistName}." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-futurism", "label_fr": "Art Futuriste", "label_es": "Arte Futurista", "label_en": "Futurism", "instruction_fr": "Applique un style futuriste, en mettant l'accent sur la vitesse, la technologie et le mouvement dynamique.", "instruction_es": "Aplica un estilo futurista, enfatizando la velocidad, la tecnología y el movimiento dinámico.", "instruction_en": "Apply a Futurist style, emphasizing speed, technology, and dynamic movement." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-impressionism", "label_fr": "Impressionnisme", "label_es": "Impresionismo", "label_en": "Impressionism", "instruction_fr": "Applique un style impressionniste, avec des touches de pinceau visibles et un focus sur la lumière.", "instruction_es": "Aplica un estilo impresionista, con pinceladas visibles y un enfoque en la luz.", "instruction_en": "Apply an impressionistic style, with visible brush strokes and a focus on light." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-ink_painting", "label_fr": "Peinture à l'Encre", "label_es": "Pintura a Tinta", "label_en": "Ink Painting", "instruction_fr": "Utilise un style de peinture à l'encre, comme la calligraphie asiatique, avec des coups de pinceau expressifs et des lavis d'encre.", "instruction_es": "Utiliza un estilo de pintura a tinta, como la caligrafía asiática, con pinceladas expresivas y aguadas de tinta.", "instruction_en": "Use an ink painting style, like Asian calligraphy, with expressive brushstrokes and ink washes." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-land_art", "label_fr": "Land Art", "label_es": "Land Art", "label_en": "Land Art", "instruction_fr": "Représente la scène comme une œuvre de 'land art', en utilisant des matériaux naturels comme la terre, les rochers et les plantes.", "instruction_es": "Representa la escena como una obra de 'land art', utilizando materiales naturales como tierra, rocas y plantas.", "instruction_en": "Depict the scene as a work of 'land art', using natural materials like earth, rocks, and plants." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-minimalism", "label_fr": "Minimalisme", "label_es": "Minimalismo", "label_en": "Minimalism", "instruction_fr": "Adopte un style minimaliste, en simplifiant la composition à ses éléments essentiels et en utilisant un espace négatif.", "instruction_es": "Adopta un estilo minimalista, simplificando la composición a sus elementos esenciales y utilizando espacio negativo.", "instruction_en": "Adopt a minimalist style, simplifying the composition to its essential elements and using negative space." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-mosaic", "label_fr": "Mosaïque", "label_es": "Mosaico", "label_en": "Mosaic", "instruction_fr": "Transforme l'image en une mosaïque, composée de petites pièces de carrelage, de verre ou de pierre.", "instruction_es": "Transforma la imagen en un mosaico, compuesto por pequeñas piezas de azulejo, vidrio o piedra.", "instruction_en": "Transform the image into a mosaic, composed of small pieces of tile, glass, or stone." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-naive_art", "label_fr": "Art Naïf", "label_es": "Arte Naíf", "label_en": "Naive Art", "instruction_fr": "Crée l'image dans un style d'art naïf, avec une simplicité enfantine, des couleurs vives et un manque de perspective formelle.", "instruction_es": "Crea la imagen en un estilo de arte naíf, con una simplicidad infantil, colores brillantes y falta de perspectiva formal.", "instruction_en": "Create the image in a Naive Art style, with a childlike simplicity, bright colors, and a lack of formal perspective." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-neoclassicism", "label_fr": "Néoclassicisme", "label_es": "Neoclasicismo", "label_en": "Neoclassicism", "instruction_fr": "Donne à la scène un style néoclassique, inspiré de l'art de la Grèce antique et de Rome, avec de l'ordre, de la clarté et de l'héroïsme.", "instruction_es": "Dale a la escena un estilo neoclásico, inspirado en el arte de la antigua Grecia y Roma, con orden, claridad y heroísmo.", "instruction_en": "Give the scene a Neoclassical style, inspired by the art of ancient Greece and Rome, with order, clarity, and heroism." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-oil_painting", "label_fr": "Peinture à l'Huile", "label_es": "Pintura al Óleo", "label_en": "Oil Painting", "instruction_fr": "Donne un style de peinture à l'huile avec des textures de pinceau.", "instruction_es": "Dale un estilo de pintura al óleo con texturas de pincel.", "instruction_en": "Give an oil painting style with brush textures." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-op_art", "label_fr": "Op Art", "label_es": "Op Art", "label_en": "Op Art", "instruction_fr": "Utilise le style 'Op Art' pour créer des illusions d'optique, avec des motifs géométriques qui semblent bouger ou vibrer.", "instruction_es": "Utiliza el estilo 'Op Art' para crear ilusiones ópticas, con patrones geométricos que parecen moverse o vibrar.", "instruction_en": "Use an 'Op Art' style to create optical illusions, with geometric patterns that seem to move or vibrate." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-sketch", "label_fr": "Croquis (Crayon)", "label_es": "Boceto (Lápiz)", "label_en": "Pencil Sketch", "instruction_fr": "Convertis l'image en un croquis au crayon détaillé.", "instruction_es": "Convierte la imagen en un boceto a lápiz detallado.", "instruction_en": "Convert the image into a detailed pencil sketch." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-photorealistic", "label_fr": "Photoréaliste", "label_es": "Fotorrealista", "label_en": "Photorealistic", "instruction_fr": "Le style final doit être photoréaliste, comme une photo.", "instruction_es": "El estilo final debe ser fotorrealista, como una foto.", "instruction_en": "The final style should be photorealistic, like a photo." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-pixel_art", "label_fr": "Pixel Art", "label_es": "Pixel Art", "label_en": "Pixel Art", "instruction_fr": "Transforme l'image en 'pixel art' (style 16 bits).", "instruction_es": "Transforma la imagen en 'pixel art' (estilo 16 bits).", "instruction_en": "Transform the image into 'pixel art' (16-bit style)." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-pointillism", "label_fr": "Pointillisme", "label_es": "Puntillismo", "label_en": "Pointillism", "instruction_fr": "Applique un style de pointillisme, en créant l'image à partir de petits points de couleur distincts.", "instruction_es": "Aplica un estilo de puntillismo, creando la imagen a partir de pequeños puntos de color distintos.", "instruction_en": "Apply a pointillism style, creating the image from small, distinct dots of color." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-pop_art", "label_fr": "Pop Art", "label_es": "Pop Art", "label_en": "Pop Art", "instruction_fr": "Utilise un style Pop Art, inspiré de la publicité et de la bande dessinée, avec des couleurs vives et des motifs répétitifs.", "instruction_es": "Utiliza un estilo Pop Art, inspirado en la publicidad y los cómics, con colores brillantes y patrones repetitivos.", "instruction_en": "Use a Pop Art style, inspired by advertising and comics, with bright colors and repetitive patterns." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-post_impressionism", "label_fr": "Post-Impressionnisme", "label_es": "Postimpresionismo", "label_en": "Post-Impressionism", "instruction_fr": "Applique un style post-impressionniste, en mettant l'accent sur le contenu émotionnel et la forme symbolique, avec des couleurs vives et des coups de pinceau distincts.", "instruction_es": "Aplica un estilo postimpresionista, enfatizando el contenido emocional y la forma simbólica, con colores vivos y pinceladas distintivas.", "instruction_en": "Apply a Post-Impressionist style, emphasizing emotional content and symbolic form, with vivid colors and distinct brushstrokes." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-realism", "label_fr": "Réalisme", "label_es": "Realismo", "label_en": "Realism", "instruction_fr": "Représente la scène avec un haut degré de réalisme, en capturant les détails et les textures de manière fidèle.", "instruction_es": "Representa la escena con un alto grado de realismo, capturando los detalles y las texturas de manera fiel.", "instruction_en": "Depict the scene with a high degree of realism, capturing details and textures faithfully." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-sci_fi", "label_fr": "Science-Fiction Futuriste", "label_es": "Ciencia Ficción Futurista", "label_en": "Futuristic Sci-Fi", "instruction_fr": "Transforme la scène dans une esthétique de science-fiction, avec des éléments futuristes, des vaisseaux spatiaux ou une technologie avancée.", "instruction_es": "Transforma la escena en una estética de ciencia ficción, con elementos futuristas, naves espaciales o tecnología avanzada.", "instruction_en": "Transform the scene with a science fiction aesthetic, featuring futuristic elements, spaceships, or advanced technology." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-street_art", "label_fr": "Street Art", "label_es": "Arte Callejero", "label_en": "Street Art", "instruction_fr": "Donne à l'image un aspect de 'street art', avec des éléments de graffiti, de pochoirs et de peintures murales.", "instruction_es": "Dale a la imagen un aspecto de 'arte callejero', con elementos de graffiti, plantillas y murales.", "instruction_en": "Give the image a 'street art' look, with elements of graffiti, stencils, and murals." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-surrealism", "label_fr": "Surréalisme", "label_es": "Surrealismo", "label_en": "Surrealism", "instruction_fr": "Transforme la scène dans un style surréaliste et onirique, défiant la logique.", "instruction_es": "Transforma la escena en un estilo surrealista y onírico, desafiando la lógica.", "instruction_en": "Transform the scene into a dreamlike, surrealist style, defying logic." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-vintage", "label_fr": "Vintage", "label_es": "Vintage", "label_en": "Vintage", "instruction_fr": "Donne à l'image un aspect ancien ou vintage.", "instruction_es": "Dale a la imagen un aspecto antiguo o vintage.", "instruction_en": "Give the image an old or vintage look." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-vintage_film", "label_fr": "Film d'Époque", "label_es": "Película Antigua", "label_en": "Vintage Film", "instruction_fr": "Donne à l'image l'aspect d'une vieille pellicule de film, avec des couleurs délavées, du grain et de légères imperfections.", "instruction_es": "Dale a la imagen el aspecto de una vieja película, con colores desvaídos, grano y ligeras imperfecciones.", "instruction_en": "Give the image the look of an old film stock, with faded colors, grain, and slight imperfections." },
      { "categoryKey": "artistic_styles", "valueKey": "artistic_styles-watercolor", "label_fr": "Aquarelle", "label_es": "Acuarela", "label_en": "Watercolor", "instruction_fr": "Applique un style d'aquarelle avec des couleurs douces.", "instruction_es": "Aplica un estilo de acuarela con colores suaves.", "instruction_en": "Apply a watercolor style with soft colors." }
    ]
  },
  "subject_edit": {
    "category_fr": "Modification du Sujet", "category_es": "Edición de Sujeto", "category_en": "Subject Editing",
    "description_fr": "Modifiez ou remplacez le sujet principal.", "description_es": "Modifica o reemplaza el sujeto principal.", "description_en": "Modify or replace the main subject.",
    "transformations": [
      { "categoryKey": "subject_edit", "valueKey": "subject_edit-to_female", "label_fr": "Transformer en Femme", "label_es": "Transformar en Mujer", "label_en": "Transform to Woman", "instruction_fr": "Transforme le sujet principal en femme, en adaptant le visage et la morphologie.", "instruction_es": "Transforma al sujeto principal en mujer, adaptando rostro y morfología.", "instruction_en": "Transform the main subject into a woman, adapting face and morphology." },
      { "categoryKey": "subject_edit", "valueKey": "subject_edit-to_male", "label_fr": "Transformer en Homme", "label_es": "Transformar en Hombre", "label_en": "Transform to Man", "instruction_fr": "Transforme le sujet principal en homme, en adaptant le visage et la morphologie.", "instruction_es": "Transforma al sujeto principal en hombre, adaptando rostro y morfología.", "instruction_en": "Transform the main subject into a man, adapting face and morphology." },
      { "categoryKey": "subject_edit", "valueKey": "subject_edit-add_person", "label_fr": "Ajouter une Personne", "label_es": "Añadir una Persona", "label_en": "Add a Person", "instruction_fr": "Ajoute une nouvelle personne dans la scène, en respectant le style.", "instruction_es": "Añade una nueva persona a la escena, respetando el estilo.", "instruction_en": "Add a new person into the scene, matching the style." },
      { "categoryKey": "subject_edit", "valueKey": "subject_edit-change_background", "label_fr": "Changer l'Arrière-plan", "label_es": "Cambiar el Fondo", "label_en": "Change Background", "instruction_fr": "Conserve le sujet mais remplace complètement l'arrière-plan.", "instruction_es": "Conserva al sujeto pero reemplaza completamente el fondo.", "instruction_en": "Keep the subject but completely replace the background." }
    ]
  },
  "effects_filters": {
    "category_fr": "Effets & Filtres", "category_es": "Efectos y Filtros", "category_en": "Effects & Filters",
    "description_fr": "Ajoutez des touches finales pour un style unique.", "description_es": "Añade toques finales para un estilo único.", "description_en": "Add final touches for a unique style.",
    "transformations": [
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-cinematic", "label_fr": "Éclairage Cinématographique", "label_es": "Iluminación Cinematográfica", "label_en": "Cinematic Lighting", "instruction_fr": "Applique un éclairage et un étalonnage des couleurs cinématographiques.", "instruction_es": "Aplica una iluminación y gradación de color cinematográficas.", "instruction_en": "Apply cinematic lighting and color grading." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-volumetric", "label_fr": "Éclairage Volumétrique", "label_es": "Iluminación Volumétrica", "label_en": "Volumetric Lighting", "instruction_fr": "Ajoute des rayons de lumière visibles (éclairage volumétrique).", "instruction_es": "Añade rayos de luz visibles (iluminación volumétrica).", "instruction_en": "Add visible light rays (volumetric lighting)." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-lens_flare", "label_fr": "Reflet d'objectif", "label_es": "Destello de lente", "label_en": "Lens Flare", "instruction_fr": "Simule un effet de reflet d'objectif, en ajoutant une source de lumière vive et son artefact caractéristique à l'image.", "instruction_es": "Simula un efecto de destello de lente, añadiendo una fuente de luz brillante y su artefacto característico a la imagen.", "instruction_en": "Simulate a lens flare effect, adding a bright light source and its characteristic artifact to the image." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-motion_blur", "label_fr": "Flou de Mouvement", "label_es": "Desenfoque de Movimiento", "label_en": "Motion Blur", "instruction_fr": "Ajoute un flou de mouvement pour simuler la vitesse.", "instruction_es": "Añade un desenfoque de movimiento para simular velocidad.", "instruction_en": "Add motion blur to simulate speed." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-film_grain", "label_fr": "Grain de Film", "label_es": "Grano de Película", "label_en": "Film Grain", "instruction_fr": "Ajoute un grain de film subtil pour un look analogique.", "instruction_es": "Añade un sutil grano de película para un look analógico.", "instruction_en": "Add subtle film grain for an analog look." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-sharpen", "label_fr": "Netteté", "label_es": "Nitidez", "label_en": "Sharpen", "instruction_fr": "Augmente la définition des bords dans l'image pour une apparence plus nette.", "instruction_es": "Aumenta la definición de los bordes en la imagen para una apariencia más nítida.", "instruction_en": "Increase the definition of edges in the image for a sharper appearance." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-noise_reduction", "label_fr": "Réduction de Bruit", "label_es": "Reducción de Ruido", "label_en": "Noise Reduction", "instruction_fr": "Réduis le bruit numérique et le grain pour une image plus nette et plus lisse.", "instruction_es": "Reduce el ruido digital y el grano para una imagen más nítida y suave.", "instruction_en": "Reduce digital noise and grain for a cleaner, smoother image." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-sepia", "label_fr": "Sépia", "label_es": "Sepia", "label_en": "Sepia", "instruction_fr": "Applique un ton sépia à l'image, lui donnant une teinte brunâtre et vintage.", "instruction_es": "Aplica un tono sepia a la imagen, dándole un matiz marrón y vintage.", "instruction_en": "Apply a sepia tone to the image, giving it a vintage, brownish hue." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-vignette", "label_fr": "Vignettage", "label_es": "Viñeteado", "label_en": "Vignette", "instruction_fr": "Applique un vignettage (assombrir les coins).", "instruction_es": "Aplica un viñeteado (oscurecer las esquinas).", "instruction_en": "Apply a vignette (darken the corners)." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-atmospheric", "label_fr": "Atmosphérique", "label_es": "Atmosférico", "label_en": "Atmospheric", "instruction_fr": "Ajoute des éléments atmosphériques (brouillard, brume, poussière).", "instruction_es": "Añade elementos atmosféricos (niebla, bruma, polvo).", "instruction_en": "Add atmospheric elements (fog, mist, dust)." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-fog", "label_fr": "Brouillard", "label_es": "Niebla", "label_en": "Fog", "instruction_fr": "Ajoute un effet de brouillard dense à la scène, obscurcissant les objets lointains et créant une atmosphère mystérieuse.", "instruction_es": "Añade un denso efecto de niebla a la escena, oscureciendo los objetos distantes y creando una atmósfera misteriosa.", "instruction_en": "Add a dense fog effect to the scene, obscuring distant objects and creating a mysterious atmosphere." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-glitch", "label_fr": "Glitch", "label_es": "Glitch", "label_en": "Glitch", "instruction_fr": "Applique un effet de 'glitch' numérique, avec des artefacts visuels, des décalages de couleur et une distorsion, comme si l'image était corrompue.", "instruction_es": "Aplica un efecto de 'glitch' digital, con artefactos visuales, desplazamientos de color y distorsión, como si la imagen estuviera corrupta.", "instruction_en": "Apply a digital 'glitch' effect, with visual artifacts, color shifts, and distortion, as if the image is corrupted." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-underwater", "label_fr": "Sous l'eau", "label_es": "Bajo el agua", "label_en": "Underwater", "instruction_fr": "Donne à la scène une atmosphère sous-marine, avec une lumière diffuse, des bulles et une palette de couleurs bleues et vertes.", "instruction_es": "Dale a la escena una atmósfera submarina, con luz difusa, burbujas y una paleta de colores azules y verdes.", "instruction_en": "Give the scene an underwater atmosphere, with diffused light, bubbles, and a blue-green color palette." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-posterize", "label_fr": "Postérisation", "label_es": "Posterizar", "label_en": "Posterize", "instruction_fr": "Réduis le nombre de couleurs pour créer un effet d'affiche (posterize).", "instruction_es": "Reduce el número de colores para crear una apariencia de póster.", "instruction_en": "Reduce the number of colors to create a poster-like appearance." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-retro_vhs", "label_fr": "Rétro VHS", "label_es": "Retro VHS", "label_en": "Retro VHS", "instruction_fr": "Applique un effet VHS vintage avec des bavures de couleur, des lignes de balayage et un léger bruit.", "instruction_es": "Aplica un efecto VHS vintage con sangrado de color, líneas de escaneo y un ligero ruido.", "instruction_en": "Apply a vintage VHS effect with color bleeding, scanlines, and slight noise." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-dreamy_pastel", "label_fr": "Pastel Onirique", "label_es": "Pastel Onírico", "label_en": "Dreamy Pastel", "instruction_fr": "Crée une atmosphère onirique avec des couleurs pastel douces, un flou artistique et une lueur légère.", "instruction_es": "Crea una atmósfera onírica con colores pastel suaves, un enfoque suave y un brillo ligero.", "instruction_en": "Create a dreamlike atmosphere with soft pastel colors, soft focus, and a gentle glow." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-noir_contrast", "label_fr": "Contraste Noir", "label_es": "Contraste Noir", "label_en": "Noir Contrast", "instruction_fr": "Applique un filtre noir et blanc à fort contraste avec des ombres dramatiques, style film noir.", "instruction_es": "Aplica un filtro de blanco y negro de alto contraste con sombras dramáticas, estilo cine negro.", "instruction_en": "Apply a high-contrast black and white filter with dramatic shadows, film noir style." },
      { "categoryKey": "effects_filters", "valueKey": "effects_filters-golden_cinema", "label_fr": "Cinéma Doré", "label_es": "Cine Dorado", "label_en": "Golden Cinema", "instruction_fr": "Combine un éclairage cinématographique avec les tons chauds de l'heure dorée.", "instruction_es": "Combina una iluminación cinematográfica con los tonos cálidos de la hora dorada.", "instruction_en": "Combine cinematic lighting with the warm tones of the golden hour." }
    ]
  },
  "lighting": {
    "category_fr": "Éclairage", "category_es": "Iluminación", "category_en": "Lighting",
    "description_fr": "Contrôlez l'ambiance et l'atmosphère avec la lumière.", "description_es": "Controla el ambiente y la atmósfera con la luz.", "description_en": "Control the mood and atmosphere with light.",
    "transformations": [
      { "categoryKey": "lighting", "valueKey": "lighting-natural_light", "label_fr": "Lumière Naturelle", "label_es": "Luz Natural", "label_en": "Natural Lighting", "instruction_fr": "Utilise la lumière naturelle (soleil, fenêtre) comme source principale.", "instruction_es": "Utiliza luz natural (sol, ventana) como fuente principal.", "instruction_en": "Use natural light (sun, window) as the main source." },
      { "categoryKey": "lighting", "valueKey": "lighting-backlighting", "label_fr": "Contre-jour", "label_es": "Contraluz", "label_en": "Backlighting", "instruction_fr": "Place la source de lumière derrière le sujet (contre-jour).", "instruction_es": "Coloca la fuente de luz detrás del sujeto (contraluz).", "instruction_en": "Place the light source behind the subject (backlighting)." },
      { "categoryKey": "lighting", "valueKey": "lighting-studio_light", "label_fr": "Éclairage Studio", "label_es": "Luz de Estudio", "label_en": "Studio Lighting", "instruction_fr": "Simule un éclairage de studio professionnel (ex: 3 points).", "instruction_es": "Simula una iluminación de estudio profesional (ej: 3 puntos).", "instruction_en": "Simulate professional studio lighting (e.g., 3-point)." },
      { "categoryKey": "lighting", "valueKey": "lighting-golden_hour", "label_fr": "Golden Hour", "label_es": "Hora Dorada", "label_en": "Golden Hour", "instruction_fr": "Baigne la scène dans la lumière chaude de la 'golden hour'.", "instruction_es": "Baña la escena en la cálida luz de la 'hora dorada'.", "instruction_en": "Bathe the scene in the warm light of the 'golden hour'." },
      { "categoryKey": "lighting", "valueKey": "lighting-neon", "label_fr": "Néon", "label_es": "Neón", "label_en": "Neon", "instruction_fr": "Ajoute un éclairage néon vibrant à la scène.", "instruction_es": "Añade una vibrante iluminación de neón a la escena.", "instruction_en": "Add vibrant neon lighting to the scene." },
      { "categoryKey": "lighting", "valueKey": "lighting-chiaroscuro", "label_fr": "Clair-Obscur", "label_es": "Claroscuro", "label_en": "Chiaroscuro", "instruction_fr": "Utilise un éclairage en clair-obscur (contraste lumière/ombre).", "instruction_es": "Utiliza una iluminación de claroscuro (contraste luz/sombra).", "instruction_en": "Use chiaroscuro lighting (light/shadow contrast)." },
      { "categoryKey": "lighting", "valueKey": "lighting-soft_light", "label_fr": "Lumière Douce", "label_es": "Luz Suave", "label_en": "Soft Light", "instruction_fr": "Utilise une lumière douce et diffuse pour minimiser les ombres et flatter le sujet.", "instruction_es": "Utiliza una luz suave y difusa para minimizar las sombras y favorecer al sujeto.", "instruction_en": "Use soft, diffuse lighting to minimize shadows and flatter the subject." },
      { "categoryKey": "lighting", "valueKey": "lighting-hard_light", "label_fr": "Lumière Dure", "label_es": "Luz Dura", "label_en": "Hard Light", "instruction_fr": "Utilise une lumière dure pour créer des ombres nettes et un fort contraste dramatique.", "instruction_es": "Utiliza una luz dura para crear sombras nítidas y un fuerte contraste dramático.", "instruction_en": "Use hard lighting to create sharp shadows and strong dramatic contrast." },
      { "categoryKey": "lighting", "valueKey": "lighting-diffused_light", "label_fr": "Lumière Diffuse", "label_es": "Luz Difusa", "label_en": "Diffused Light", "instruction_fr": "Disperse la lumière pour créer une lueur douce et uniforme sans ombres dures.", "instruction_es": "Dispersa la luz para crear un brillo suave y uniforme sin sombras duras.", "instruction_en": "Scatter the light to create a soft, even glow without harsh shadows." },
      { "categoryKey": "lighting", "valueKey": "lighting-side_lighting", "label_fr": "Lumière Latérale", "label_es": "Iluminación Lateral", "label_en": "Side Lighting", "instruction_fr": "Illumine le sujet par le côté pour accentuer la texture et le volume.", "instruction_es": "Ilumina al sujeto desde el lado para acentuer la textura y el volumen.", "instruction_en": "Illuminate the subject from the side to emphasize texture and volume." },
      { "categoryKey": "lighting", "valueKey": "lighting-butterfly_lighting", "label_fr": "Éclairage Papillon", "label_es": "Iluminación Mariposa", "label_en": "Butterfly Lighting", "instruction_fr": "Place la lumière principale au-dessus et devant le visage pour créer une ombre sous le nez.", "instruction_es": "Coloca la luz principal arriba y delante de la cara para crear una sombra debajo de la nariz.", "instruction_en": "Place the main light above and in front of the face to create a shadow under the nose." },
      { "categoryKey": "lighting", "valueKey": "lighting-rim_lighting", "label_fr": "Éclairage de Contour (Rim)", "label_es": "Iluminación de Borde", "label_en": "Rim Lighting", "instruction_fr": "Illumine les bords du sujet par l'arrière pour le détacher du fond (rim light).", "instruction_es": "Ilumina los bordes del sujeto desde atrás para separarlo del fondo.", "instruction_en": "Illuminate the edges of the subject from behind to separate them from the background." },
      { "categoryKey": "lighting", "valueKey": "lighting-high_key", "label_fr": "Lumière High Key", "label_es": "Iluminación High Key", "label_en": "High Key Lighting", "instruction_fr": "Utilise un éclairage très lumineux et uniforme, avec peu d'ombres et des tons clairs prédominants.", "instruction_es": "Utiliza una iluminación muy brillante y uniforme, con pocas sombras y tonos claros predominantes.", "instruction_en": "Use very bright, even lighting, with few shadows and predominant light tones." },
      { "categoryKey": "lighting", "valueKey": "lighting-low_key", "label_fr": "Lumière Low Key", "label_es": "Iluminación Low Key", "label_en": "Low Key Lighting", "instruction_fr": "Utilise des tons sombres, des noirs profonds et un éclairage sélectif pour une ambiance mystérieuse.", "instruction_es": "Utiliza tonos oscuros, negros profundos e iluminación selectiva para un ambiente misterioso.", "instruction_en": "Use dark tones, deep blacks, and selective lighting for a mysterious mood." },
      { "categoryKey": "lighting", "valueKey": "lighting-blue_hour", "label_fr": "L'Heure Bleue / Entre Chien et Loup", "label_es": "Hora Azul", "label_en": "Blue Hour", "instruction_fr": "Capture l'ambiance entre chien et loup, avec le ciel bleu profond du crépuscule.", "instruction_es": "Captura el ambiente de la hora azul, con el cielo azul profundo del crepúsculo.", "instruction_en": "Capture the blue hour atmosphere, with the deep blue sky of twilight." }
    ]
  },
  "mood": {
    "category_fr": "Ambiance", "category_es": "Ambiente", "category_en": "Mood",
    "description_fr": "Évoquez une émotion ou un sentiment spécifique.", "description_es": "Evoca una emoción o sentimiento específico.", "description_en": "Evoke a specific emotion or feeling.",
    "transformations": [
      { "categoryKey": "mood", "valueKey": "mood-dramatic", "label_fr": "Dramatique", "label_es": "Dramático", "label_en": "Dramatic", "instruction_fr": "Insuffle une ambiance sombre et dramatique.", "instruction_es": "Infunde un ambiente oscuro y dramático.", "instruction_en": "Infuse a dark and dramatic mood." },
      { "categoryKey": "mood", "valueKey": "mood-joyful", "label_fr": "Joyeux / Optimiste", "label_es": "Alegre / Optimista", "label_en": "Joyful / Optimistic", "instruction_fr": "Rends l'ambiance joyeuse et optimiste.", "instruction_es": "Haz que el ambiente sea alegre y optimista.", "instruction_en": "Make the mood joyful and optimistic." },
      { "categoryKey": "mood", "valueKey": "mood-calm", "label_fr": "Calme / Serein", "label_es": "Calmo / Sereno", "label_en": "Calm / Serene", "instruction_fr": "Crée une ambiance calme et sereine.", "instruction_es": "Crea un ambiente calmo y sereno.", "instruction_en": "Create a calm and serene mood." },
      { "categoryKey": "mood", "valueKey": "mood-mysterious", "label_fr": "Mystérieux", "label_es": "Misterioso", "label_en": "Mysterious", "instruction_fr": "Crée une ambiance mystérieuse (brouillard, ombres).", "instruction_es": "Crea un ambiente misterioso (niebla, sombras).", "instruction_en": "Create a mysterious mood (fog, shadows)." },
      { "categoryKey": "mood", "valueKey": "mood-melancholic", "label_fr": "Mélancolique / Nostalgique", "label_es": "Melancólico / Nostálgico", "label_en": "Melancholic / Nostalgic", "instruction_fr": "Évoque une atmosphère mélancolique et nostalgique.", "instruction_es": "Evoca una atmósfera melancólica y nostálgica.", "instruction_en": "Evoke a melancholic and nostalgic atmosphere." },
      { "categoryKey": "mood", "valueKey": "mood-romantic", "label_fr": "Romantique / Passionné", "label_es": "Romántico / Apasionado", "label_en": "Romantic / Passionate", "instruction_fr": "Crée une ambiance romantique et passionnée.", "instruction_es": "Crea un ambiente romántico y apasionado.", "instruction_en": "Create a romantic and passionate mood." },
      { "categoryKey": "mood", "valueKey": "mood-lonely", "label_fr": "Solitaire / Isolé", "label_es": "Solitario / Aislado", "label_en": "Lonely / Isolated", "instruction_fr": "Suggère la solitude et l'isolement.", "instruction_es": "Sugiere soledad y aislamiento.", "instruction_en": "Suggest loneliness and isolation." },
      { "categoryKey": "mood", "valueKey": "mood-sad", "label_fr": "Triste / Désespéré", "label_es": "Triste / Desesperado", "label_en": "Sad / Desperate", "instruction_fr": "Exprime la tristesse ou le désespoir.", "instruction_es": "Expresa tristeza o desesperación.", "instruction_en": "Express sadness or desperation." },
      { "categoryKey": "mood", "valueKey": "mood-laughing", "label_fr": "Rieur", "label_es": "Risueño / Alegre", "label_en": "Laughing / Cheerful", "instruction_fr": "Crée une ambiance rieuse et pleine de gaieté.", "instruction_es": "Crea un ambiente risueño y alegre.", "instruction_en": "Create a laughing and cheerful mood." },
      { "categoryKey": "mood", "valueKey": "mood-stern", "label_fr": "Sévère", "label_es": "Severo / Estricto", "label_en": "Stern / Severe", "instruction_fr": "Installe une atmosphère sévère et stricte.", "instruction_es": "Instala una atmósfera severa y estricta.", "instruction_en": "Establish a stern and severe atmosphere." },
      { "categoryKey": "mood", "valueKey": "mood-angry", "label_fr": "Colérique", "label_es": "Colérico / Iracundo", "label_en": "Angry / Short-tempered", "instruction_fr": "Évoque la colère et l'irritation.", "instruction_es": "Evoca cólera e ira.", "instruction_en": "Evoke anger and short temper." },
      { "categoryKey": "mood", "valueKey": "mood-cozy", "label_fr": "Cosy / Chaleureux", "label_es": "Acogedor / Cálido", "label_en": "Cozy / Warm", "instruction_fr": "Crée une ambiance cosy et chaleureuse.", "instruction_es": "Crea un ambiente acogedor y cálido.", "instruction_en": "Create a cozy and warm atmosphere." },
      { "categoryKey": "mood", "valueKey": "mood-ethereal", "label_fr": "Éthéré / Onirique", "label_es": "Etéreo / Onírico", "label_en": "Ethereal / Dreamy", "instruction_fr": "Donne un aspect éthéré et onirique.", "instruction_es": "Dale un aspecto etéreo y onírico.", "instruction_en": "Give an ethereal and dreamy look." }
    ]
  },
  "complexity": {
    "category_fr": "Niveau de Détail", "category_es": "Nivel de Detalle", "category_en": "Level of Detail",
    "description_fr": "Contrôlez la densité visuelle, du minimalisme au maximalisme.", "description_es": "Controla la densidad visual, desde el minimalismo hasta el maximalismo.", "description_en": "Control visual density, from minimalism to maximalism.",
    "transformations": [
      { "categoryKey": "complexity", "valueKey": "complexity-minimalist", "label_fr": "Minimaliste", "label_es": "Minimalista", "label_en": "Minimalist", "instruction_fr": "Utilise très peu de détails, un espace négatif abondant et des lignes épurées.", "instruction_es": "Utiliza muy pocos detalles, abundante espacio negativo y líneas limpias.", "instruction_en": "Use very few details, abundant negative space, and clean lines." },
      { "categoryKey": "complexity", "valueKey": "complexity-simple", "label_fr": "Simple", "label_es": "Simple", "label_en": "Simple", "instruction_fr": "Garde la composition simple et non encombrée.", "instruction_es": "Mantén la composición simple y despejada.", "instruction_en": "Keep the composition simple and uncluttered." },
      { "categoryKey": "complexity", "valueKey": "complexity-detailed", "label_fr": "Détaillé", "label_es": "Detallado", "label_en": "Detailed", "instruction_fr": "Ajoute un niveau élevé de détails et de textures riches.", "instruction_es": "Añade un alto nivel de detalles y texturas ricas.", "instruction_en": "Add a high level of detail and rich textures." },
      { "categoryKey": "complexity", "valueKey": "complexity-intricate", "label_fr": "Complexe", "label_es": "Intrincado", "label_en": "Intricate", "instruction_fr": "Crée une composition très complexe et élaborée.", "instruction_es": "Crea una composición muy compleja y elaborada.", "instruction_en": "Create a highly complex and elaborate composition." },
      { "categoryKey": "complexity", "valueKey": "complexity-maximalist", "label_fr": "Hyper-Détaillé / Maximaliste", "label_es": "Hiperdetallado / Maximalista", "label_en": "Hyper-Detailed / Maximalist", "instruction_fr": "Utilise des détails extrêmes, remplissant chaque espace (horror vacui).", "instruction_es": "Utiliza detalles extremos, llenando cada espacio (horror vacui).", "instruction_en": "Use extreme detail, filling every space (horror vacui)." }
    ]
  },
  "lenses": {
    "category_fr": "Objectifs photo", "category_es": "Lentes", "category_en": "Lenses",
    "description_fr": "Simulez différents objectifs pour des effets uniques.", "description_es": "Simula diferentes lentes de cámara para efectos únicos.", "description_en": "Simulate different camera lenses for unique effects.",
    "transformations": [
      { "categoryKey": "lenses", "valueKey": "lenses-wide_angle_lens", "label_fr": "Objectif Grand Angle", "label_es": "Lente Gran Angular", "label_en": "Wide-Angle Lens", "instruction_fr": "Simule un objectif grand angle (ex: 24mm) pour une perspective large.", "instruction_es": "Simula una lente gran angular (ej: 24mm) para una perspectiva amplia.", "instruction_en": "Simulate a wide-angle lens (e.g., 24mm) for a broad perspective." },
      { "categoryKey": "lenses", "valueKey": "lenses-telephoto_lens", "label_fr": "Téléobjectif", "label_es": "Teleobjetivo", "label_en": "Telephoto Lens", "instruction_fr": "Simule un téléobjectif (ex: 135mm) pour compresser la perspective.", "instruction_es": "Simula un teleobjetivo (ej: 135mm) para comprimir la perspectiva.", "instruction_en": "Simulate a telephoto lens (e.g., 135mm) to compress perspective." },
      { "categoryKey": "lenses", "valueKey": "lenses-macro_lens", "label_fr": "Objectif Macro", "label_es": "Lente Macro", "label_en": "Macro Lens", "instruction_fr": "Simule un objectif macro pour des gros plans extrêmes.", "instruction_es": "Simula una lente macro para primeros planos extremos.", "instruction_en": "Simulate a macro lens for extreme close-ups." },
      { "categoryKey": "lenses", "valueKey": "lenses-bokeh", "label_fr": "Bokeh", "label_es": "Bokeh", "label_en": "Bokeh", "instruction_fr": "Applique un effet bokeh prononcé, avec des orbes de lumière flous.", "instruction_es": "Aplica un fuerte efecto bokeh, con orbes de luz borrosos.", "instruction_en": "Apply a strong bokeh effect, with blurry orbs of light." }
    ]
  },
  "technical_details": {
    "category_fr": "Détails Techniques", "category_es": "Detalles Técnicos", "category_en": "Technical Details",
    "description_fr": "Imitez les paramètres d'un vrai appareil photo.", "description_es": "Imita la configuración de una cámara real para un aspecto fotográfico.", "description_en": "Mimic real camera settings for a photographic look.",
    "transformations": [
      { "categoryKey": "technical_details", "valueKey": "technical_details-low_aperture", "label_fr": "Faible Ouverture (f/1.4)", "label_es": "Apertura Baja (f/1.4)", "label_en": "Low Aperture (f/1.4)", "instruction_fr": "Utilise une faible profondeur de champ (style f/1.4) pour un arrière-plan flou.", "instruction_es": "Utiliza una profundidad de campo reducida (estilo f/1.4) para un fondo borroso.", "instruction_en": "Use a shallow depth of field (f/1.4 style) for a blurry background." },
      { "categoryKey": "technical_details", "valueKey": "technical_details-high_aperture", "label_fr": "Grande Ouverture (f/16)", "label_es": "Apertura Alta (f/16)", "label_en": "High Aperture (f/16)", "instruction_fr": "Utilise une grande profondeur de champ (style f/16) pour que tout soit net.", "instruction_es": "Utiliza una gran profundidad de campo (estilo f/16) para que todo esté nítido.", "instruction_en": "Use a deep depth of field (f/16 style) so everything is sharp." },
      { "categoryKey": "technical_details", "valueKey": "technical_details-fast_shutter", "label_fr": "Obturateur Rapide (1/1000s)", "label_es": "Obturador Rápido (1/1000s)", "label_en": "Fast Shutter (1/1000s)", "instruction_fr": "Simule un obturateur rapide (1/1000s) pour figer le mouvement.", "instruction_es": "Simula un obturador rápido (1/1000s) para congelar el movimiento.", "instruction_en": "Simulate a fast shutter (1/1000s) to freeze motion." },
      { "categoryKey": "technical_details", "valueKey": "technical_details-sharp_focus", "label_fr": "Mise au Point Nette", "label_es": "Enfoque Nítido", "label_en": "Sharp Focus", "instruction_fr": "Assure une mise au point parfaitement nette sur le sujet principal.", "instruction_es": "Asegura un enfoque perfectamente nítido en el sujeto principal.", "instruction_en": "Ensure perfectly sharp focus on the main subject." }
    ]
  }
};
